workflows:
  ios-denis-voice:
    name: Denis Voice iPad App
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Install dependencies
        script: |
          cd $CM_BUILD_DIR
          swift package resolve
      - name: Build iOS app
        script: |
          cd $CM_BUILD_DIR
          xcodebuild build -project DenisVoice.xcodeproj -scheme DenisVoice -configuration Release -destination generic/platform=iOS CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -archivePath $CM_BUILD_DIR/build/DenisVoice.xcarchive archive
      - name: Export IPA
        script: |
          cd $CM_BUILD_DIR
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/build/DenisVoice.xcarchive -exportOptionsPlist export_options.plist CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -exportPath $CM_BUILD_DIR/build/ipa
    artifacts:
      - build/ipa/*.ipa
      - build/ipa/*.dSYM.zip
